import { GuidePage, guideMetadata } from "../guide-page";
import Link from "next/link";

export const metadata = guideMetadata(
  "The Blood of Dawnwalker Review Embargo: Reviews & Platforms",
  "The Blood of Dawnwalker review embargo lifted August 31. Reviews are live: see original links, tested platforms, disclosed hardware and clearly labelled performance notes.",
  "/review-embargo",
  ["The Blood of Dawnwalker review embargo", "Blood of Dawnwalker reviews", "When do Blood of Dawnwalker reviews come out", "Blood of Dawnwalker Metacritic"]
);

export default function ReviewEmbargoPage() {
  return <GuidePage
    eyebrow="REVIEW EMBARGO · REVIEWS LIVE"
    title="The Blood of Dawnwalker review embargo: reviews, times and tested platforms"
    dek="The reported review embargo lifted on August 31 at 5:00 PM CEST and full reviews are now live. This source-by-source tracker separates each critic's opinion from the hardware, platform and technical details they actually disclose."
    checked="September 1, 2026"
    sources={[
      { label: "DawnwalkerOfficial community post — reported embargo schedule", href: "https://www.reddit.com/r/DawnwalkerOfficial/comments/1vrwcnz/the_blood_of_dawnwalker_review_embargo_lifts_on/" },
      { label: "PC Gamer — PC review and disclosed test hardware", href: "https://www.pcgamer.com/games/rpg/the-blood-of-dawnwalker-review/" },
      { label: "Game Informer — PS5 review", href: "https://gameinformer.com/review/the-blood-of-dawnwalker/time-doesnt-heal-all-wounds" },
      { label: "CGMagazine — PS5 review", href: "https://www.cgmagonline.com/review/game/blood-of-dawnwalker-review-rpg/" },
      { label: "Destructoid — PC performance observation", href: "https://www.destructoid.com/reviews/the-blood-of-dawnwalker-review/" },
      { label: "The AU Review — PS5 review-build performance notes", href: "https://www.theaureview.com/games/the-blood-of-dawnwalker-review/" },
      { label: "Metacritic — The Blood of Dawnwalker listing", href: "https://www.metacritic.com/game/the-blood-of-dawnwalker/" },
    ]}
    sections={[
      { title: "The review embargo lifted; reviews are live", body: <><p><b>Attributable full reviews published on August 31, 2026.</b> An official community post reported an embargo schedule of August 31 at 5:00 PM CEST; several outlets published finished reviews that day. We have not found a publisher press release independently confirming the exact minute, so this page records the published reviews rather than presenting the reported time as a publisher announcement.</p><p><b>Important:</b> a reviewer's conclusion is an opinion. Hardware, platform, build and measurable performance observations are listed only when that outlet states them. A single reviewer’s result is not a universal PC or console benchmark.</p></> },
      { title: "Reported local times", body: <div className="fact-grid"><p><b>Los Angeles</b>August 31 · 8:00 AM PDT</p><p><b>New York</b>August 31 · 11:00 AM EDT</p><p><b>London</b>August 31 · 4:00 PM BST</p><p><b>Warsaw / Berlin / Paris</b>August 31 · 5:00 PM CEST</p><p><b>Tokyo</b>September 1 · 12:00 AM JST</p><p><b>Sydney</b>September 1 · 1:00 AM AEST</p></div> },
      { title: "What a review embargo means", body: <p>It is the earliest scheduled time that outlets can publish full-game verdicts, scores and technical testing. It is <b>not</b> an early-access time, a preload announcement or a promise that every outlet will publish immediately. Before that time, hands-on previews and speculation are not the same as final reviews.</p> },
      { title: "First attributable full reviews", body: <div className="source-list"><p><b><a href="https://www.pcgamer.com/games/rpg/the-blood-of-dawnwalker-review/" target="_blank" rel="noreferrer">PC Gamer</a> · August 31</b><br/><b>Test platform:</b> PC — RTX 3060 laptop, Ryzen 5 5600H and 16GB RAM disclosed. <b>Patch/build:</b> not stated. <b>Technical observation:</b> the reviewer reports generally holding 60 FPS at 1080p/Low on that machine. That is one reviewer’s scene-and-settings-specific observation, not a recommended specification or guaranteed result. <b>Review observation:</b> the review praises the setting and story while finding the time system less severe than its early promise.</p><p><b><a href="https://gameinformer.com/review/the-blood-of-dawnwalker/time-doesnt-heal-all-wounds" target="_blank" rel="noreferrer">Game Informer</a> · August 31, 10:00 AM</b><br/><b>Test platform:</b> PlayStation 5. <b>Patch/build:</b> not stated. <b>Technical evidence:</b> none quantified in this review. <b>Review observation:</b> it says the 30-day structure shaped its completed playthrough, while criticising repetitive enemy encounters and some systems.</p><p><b><a href="https://www.cgmagonline.com/review/game/blood-of-dawnwalker-review-rpg/" target="_blank" rel="noreferrer">CGMagazine</a> · August 31</b><br/><b>Test platform:</b> PlayStation 5. <b>Patch/build:</b> not stated. <b>Technical evidence:</b> no versioned frame-rate test is provided. <b>Review observation:</b> it describes the day/night forms and time segments as central to how quests can be approached; it also calls combat uneven at times.</p><p><b><a href="https://www.destructoid.com/reviews/the-blood-of-dawnwalker-review/" target="_blank" rel="noreferrer">Destructoid</a> · August 31, 10:00 AM</b><br/><b>Test platform:</b> PC — the writer specifically names an RX 9070 XT at native 1440p/Ultra. <b>Patch/build:</b> not stated. <b>Technical observation:</b> the writer reports 80–90 FPS outside busy areas but drops into the 30s in Svartrau; treat that as a single pre-release test report, not a confirmed launch-wide issue or fix.</p><p><b><a href="https://www.theaureview.com/games/the-blood-of-dawnwalker-review/" target="_blank" rel="noreferrer">The AU Review</a> · September 1</b><br/><b>Test platform:</b> the reviewer calls it a final PlayStation 5 build and also mentions PS5 Pro mode comparison. <b>Patch/build:</b> a sizable review-period patch arrived roughly 30 hours into play; no build number is given. The outlet says a Day One performance mode is planned to target 60 FPS, so that result was not available for this review. <b>Technical observation:</b> the reviewer reports 40 FPS or lower during review play, pop-in and occasional clipping, and no dramatic change after the review-period patch beyond improved stability. This is one pre-launch reviewer report, not confirmation of a launch-wide defect or Day One fix.</p></div> },
      { title: "What can and cannot be concluded so far", body: <><p><b>Supported by multiple finished reviews:</b> the game’s story, world and 30-day structure are central to critics’ discussion; opinions differ on how consistently its combat and time-system ambitions land.</p><p><b>Not supported yet:</b> a universal PC benchmark, a confirmed Day One performance fix, a cross-platform performance verdict, or a reliable aggregate conclusion. Reviews do not disclose a common build or patch number, so their technical results cannot be treated as like-for-like testing.</p></> },
      { title: "Metacritic: direct listing, not a copied score roundup", body: <p>For readers searching for <i>The Blood of Dawnwalker Metacritic</i>, use the <a href="https://www.metacritic.com/game/the-blood-of-dawnwalker/" target="_blank" rel="noreferrer">live Metacritic game listing</a> to see its current status. We do not copy, calculate or repeatedly publish an aggregate score here: a changing number alone does not show which platform was reviewed, whether the critic used a launch patch, or what technical evidence the review contains. This page links original reviews and preserves their disclosed test context instead.</p> },
      { title: "What to check when reviews go live", body: <ul><li><b>Platform and patch:</b> PC, PS5 and Xbox results are not interchangeable, especially before the Day One update.</li><li><b>Completion status:</b> distinguish a finished review from a limited preview or review-in-progress.</li><li><b>Performance evidence:</b> look for tested settings, console mode, frame-rate measurements and repeatable scenes.</li><li><b>30-day system:</b> check whether the reviewer explains actual time costs rather than repeating pre-release assumptions.</li><li><b>Disclosure:</b> note review code, sponsored travel or other access disclosed by the outlet.</li></ul> },
      { title: "Should you wait before pre-ordering?", body: <p>If performance, story quality or the 30-day time system could change your buying decision, waiting for full reviews is the rational choice. The current edition listings do not promise early access; see the <Link href="/editions">edition comparison</Link> and the <Link href="/release-date">release date and unlock guide</Link> for confirmed purchase and timing details.</p> },
      { title: "Review embargo FAQ", body: <><h3>When did The Blood of Dawnwalker review embargo lift?</h3><p>The official community post reported August 31, 2026 at 5:00 PM CEST. That was a review-publication time, not early access or game unlock time.</p><h3>Are The Blood of Dawnwalker reviews live?</h3><p>Yes. The original full reviews linked above were published on August 31; previews, leaks and score screenshots are excluded.</p><h3>Does an August 31 review unlock the game?</h3><p>No. Reviews are separate from the September 3 game release and platform unlock schedule.</p><h3>Does a PC review prove performance on every PC?</h3><p>No. Compare its exact hardware, settings, location and stated game build. Until several outlets publish comparable tests or the launch build is available, no universal frame-rate conclusion is justified.</p><h3>Will this become a score roundup?</h3><p>No. It will continue to prioritise original links, disclosed test context and clearly-labelled review observations over a copied aggregate.</p></> },
    ]}
  />;
}
