import { guideMetadata, GuidePage } from "../guide-page";

export const metadata = guideMetadata("About Dawnwalker Guide", "How Dawnwalker Guide researches, updates and corrects independent The Blood of Dawnwalker help pages.", "/about", ["Dawnwalker Guide editorial policy", "The Blood of Dawnwalker guide sources"]);

export default function AboutPage() {
  return <GuidePage eyebrow="ABOUT DAWNWALKER GUIDE" title="How do we make Dawnwalker guides trustworthy?" dek="Dawnwalker Guide is an independent fan resource. We separate confirmed information from player reports and mark uncertainty rather than turning it into a claim." checked="September 5, 2026" showAds={false} sources={[{ label: "Dawnwalker Guide public correction tracker", href: "https://github.com/wencun/dawnwalker.cc/issues" }]} sections={[
    { title: "What is this site for?", body: <><p>We publish focused answers for The Blood of Dawnwalker: quest routes, game systems, launch issues, platforms and purchasing questions. This is not an official site, and it does not speak for Rebel Wolves, Bandai Namco or storefronts.</p><h3>Our editorial promise</h3><ul><li>Link readers to the original source whenever a claim comes from a developer, publisher, platform or mod author.</li><li>Label player reports as reports, not as confirmed game behaviour.</li><li>Update, correct or remove a claim when stronger evidence becomes available.</li></ul></> },
    { title: "How do we check information?", body: <><p>Each guide carries a “Last checked” date and a source list. For time-sensitive topics such as patches, release times and bugs, we prefer dated official notes, direct platform listings and reproducible steps over reposts or unsourced social posts.</p><table className="editorial-table"><caption>What readers can verify on a guide page</caption><thead><tr><th scope="col">Signal</th><th scope="col">What it means</th><th scope="col">Reader check</th></tr></thead><tbody><tr><th scope="row">Source link</th><td>The claim is tied to a named primary or relevant source.</td><td>Open the linked source and compare the wording or version.</td></tr><tr><th scope="row">Last checked</th><td>The page states when its facts were reviewed.</td><td>Treat older dates as context, not a guarantee of current status.</td></tr><tr><th scope="row">Community report</th><td>A player-observed issue has not yet become an official fact.</td><td>Compare platform, patch version and reproducible steps.</td></tr></tbody></table></> },
    { title: "How can you suggest a correction?", body: <p>Use the public feedback tracker to report an error, missing source or outdated workaround. Include the guide URL, platform, game version and a source or reproduction step when possible. We do not require an account on this site to submit feedback.</p> },
  ]} />;
}
