import { notFound } from "next/navigation";
import { RegionalGuidePage, regionalMetadata } from "../../regional-guide";

const locales = ["pl", "ru", "cs"] as const;
const topics = ["editions", "time-system", "known-issues"] as const;
type Locale = typeof locales[number];
type Topic = typeof topics[number];

const copy: Record<Locale, Record<Topic, { eyebrow: string; title: string; dek: string; section: string; body: string; nav: [string, string]; source: string; checked: string }>> = {
  pl: {
    editions: { eyebrow: "EDYCJE · POTWIERDZONE INFORMACJE", title: "Edycje The Blood of Dawnwalker", dek: "Porównanie zawartości edycji na podstawie materiałów wydawcy — bez przypisywania wersjom niepotwierdzonych bonusów.", section: "Jak porównywać edycje", body: "Sprawdź zawartość cyfrową, platformę i cenę w swoim regionalnym sklepie. Nazwa edycji nie oznacza wcześniejszego dostępu, jeśli wydawca wyraźnie tego nie potwierdził.", nav: ["Premiera", "Konsole"], source: "Oficjalna strona gry", checked: "27 sierpnia 2026" },
    "time-system": { eyebrow: "CZAS W GRZE · POTWIERDZONE MECHANIKI", title: "System czasu w The Blood of Dawnwalker", dek: "Co wiemy o 30 dniach, konsekwencjach zadań i wyborach — bez wymyślania sposobów na zatrzymanie czasu.", section: "Co potwierdzono", body: "Zadania i decyzje mogą przesuwać czas naprzód, dlatego nie da się pomóc wszystkim postaciom w jednym przejściu. Szczegóły praktyczne uzupełnimy po premierze na podstawie testów.", nav: ["Premiera", "Konsole"], source: "Oficjalna strona gry", checked: "27 sierpnia 2026" },
    "known-issues": { eyebrow: "STATUS PROBLEMÓW · RAPORTY GRACZY", title: "Znane problemy The Blood of Dawnwalker", dek: "Śledzimy awarie, wydajność i problemy z zadaniami, ale publikujemy rozwiązania dopiero po weryfikacji.", section: "Jak zgłaszać problem", body: "Dodaj platformę, wersję gry, ustawienia, dokładne kroki i nagranie lub zrzut ekranu. Pojedynczy wpis społeczności nie jest potwierdzonym problemem całej gry.", nav: ["Premiera", "Konsole"], source: "Centrum zgłoszeń", checked: "27 sierpnia 2026" },
  },
  ru: {
    editions: { eyebrow: "ИЗДАНИЯ · ПРОВЕРЕННЫЕ ДАННЫЕ", title: "Издания The Blood of Dawnwalker", dek: "Сравнение состава изданий по материалам издателя без неподтверждённых бонусов.", section: "Как сравнивать издания", body: "Проверяйте цифровой контент, платформу и цену в региональном магазине. Название издания не означает ранний доступ без прямого подтверждения издателя.", nav: ["Релиз", "Консоли"], source: "Официальная страница игры", checked: "27 августа 2026" },
    "time-system": { eyebrow: "ВРЕМЯ В ИГРЕ · ПОДТВЕРЖДЁННЫЕ МЕХАНИКИ", title: "Система времени в The Blood of Dawnwalker", dek: "Что известно о 30 днях, последствиях заданий и выборе — без выдуманных способов остановить время.", section: "Что подтверждено", body: "Задания и решения могут продвигать время, поэтому нельзя помочь всем персонажам за одно прохождение. Практические детали появятся после проверок на релизе.", nav: ["Релиз", "Консоли"], source: "Официальная страница игры", checked: "27 августа 2026" },
    "known-issues": { eyebrow: "СТАТУС ПРОБЛЕМ · ОТЧЁТЫ ИГРОКОВ", title: "Известные проблемы The Blood of Dawnwalker", dek: "Мы отслеживаем вылеты, производительность и задания, но публикуем решения только после проверки.", section: "Как сообщить о проблеме", body: "Укажите платформу, версию игры, настройки, точные шаги и приложите запись или скриншот. Один пост сообщества не доказывает проблему всей игры.", nav: ["Релиз", "Консоли"], source: "Центр сообщений", checked: "27 августа 2026" },
  },
  cs: {
    editions: { eyebrow: "EDICE · OVĚŘENÉ INFORMACE", title: "Edice The Blood of Dawnwalker", dek: "Srovnání obsahu edic podle materiálů vydavatele bez nepotvrzených bonusů.", section: "Jak porovnávat edice", body: "Ověřte digitální obsah, platformu a cenu v regionálním obchodě. Název edice neznamená dřívější přístup bez výslovného potvrzení vydavatele.", nav: ["Vydání", "Konzole"], source: "Oficiální stránka hry", checked: "27. srpna 2026" },
    "time-system": { eyebrow: "ČAS VE HŘE · POTVRZENÉ MECHANIKY", title: "Systém času v The Blood of Dawnwalker", dek: "Co víme o 30 dnech, důsledcích úkolů a volbách — bez vymyšlených způsobů, jak zastavit čas.", section: "Co je potvrzeno", body: "Úkoly a rozhodnutí mohou posouvat čas, proto nelze během jednoho průchodu pomoci všem postavám. Praktické podrobnosti doplníme po ověření při vydání.", nav: ["Vydání", "Konzole"], source: "Oficiální stránka hry", checked: "27. srpna 2026" },
    "known-issues": { eyebrow: "STAV PROBLÉMŮ · HLÁŠENÍ HRÁČŮ", title: "Známé problémy The Blood of Dawnwalker", dek: "Sledujeme pády, výkon a úkoly, ale řešení zveřejňujeme až po ověření.", section: "Jak nahlásit problém", body: "Uveďte platformu, verzi hry, nastavení, přesné kroky a záznam nebo snímek obrazovky. Jeden příspěvek komunity nedokazuje problém celé hry.", nav: ["Vydání", "Konzole"], source: "Centrum hlášení", checked: "27. srpna 2026" },
  },
};

export function generateStaticParams() { return locales.flatMap((locale) => topics.map((topic) => ({ locale, topic }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; topic: string }> }) { const { locale, topic } = await params; if (!locales.includes(locale as Locale) || !topics.includes(topic as Topic)) return {}; const item = copy[locale as Locale][topic as Topic]; return regionalMetadata(locale as "ru" | "cs", item.title, item.dek, `/${locale}/${topic}`, [item.title]); }
export default async function LocalizedInfoPage({ params }: { params: Promise<{ locale: string; topic: string }> }) { const { locale, topic } = await params; if (!locales.includes(locale as Locale) || !topics.includes(topic as Topic)) notFound(); const item = copy[locale as Locale][topic as Topic]; return <RegionalGuidePage locale={locale as Locale} eyebrow={item.eyebrow} title={item.title} dek={item.dek} checked={item.checked} homeLabel="" releaseLabel={item.nav[0]} consoleLabel={item.nav[1]} checkedLabel="✓" sourcesLabel="Sources" footer="Dawnwalker Guide" sources={[{ label: item.source, href: "https://www.bandainamcoent.com/games/dawnwalker" }]} sections={[{ title: item.section, body: <p>{item.body}</p> }]} />; }
