import { notFound } from "next/navigation";
import { RegionalGuidePage, regionalMetadata } from "../../regional-guide";

const locales = ["pl", "ru", "cs"] as const;
const topics = ["can-i-run", "editions", "time-system", "known-issues"] as const;
type Locale = typeof locales[number];
type Topic = typeof topics[number];

const copy: Record<Locale, Record<Topic, { eyebrow: string; title: string; dek: string; section: string; body: string; nav: [string, string]; source: string; checked: string }>> = {
  pl: {
    "can-i-run": { eyebrow: "KOMPATYBILNOŚĆ PC · WYMAGANIA OFICJALNE", title: "Czy mój komputer uruchomi The Blood of Dawnwalker?", dek: "Sprawdź oficjalne wymagania PC i porównaj je ze swoim sprzętem.", section: "Ważne ograniczenie", body: "Wymagania sprzętowe nie są gwarancją konkretnej liczby FPS. Wynik zależy od rozdzielczości, ustawień, sterowników i wersji gry.", nav: ["Premiera", "Konsole"], source: "Oficjalne wymagania PC", checked: "27 sierpnia 2026" },
    editions: { eyebrow: "EDYCJE · POTWIERDZONE INFORMACJE", title: "Edycje The Blood of Dawnwalker", dek: "Porównanie zawartości edycji na podstawie materiałów wydawcy — bez przypisywania wersjom niepotwierdzonych bonusów.", section: "Jak porównywać edycje", body: "Sprawdź zawartość cyfrową, platformę i cenę w swoim regionalnym sklepie. Nazwa edycji nie oznacza wcześniejszego dostępu, jeśli wydawca wyraźnie tego nie potwierdził.", nav: ["Premiera", "Konsole"], source: "Oficjalna strona gry", checked: "27 sierpnia 2026" },
    "time-system": { eyebrow: "CZAS W GRZE · POTWIERDZONE MECHANIKI", title: "System czasu w The Blood of Dawnwalker", dek: "Co wiemy o 30 dniach, konsekwencjach zadań i wyborach — bez wymyślania sposobów na zatrzymanie czasu.", section: "Co potwierdzono", body: "Zadania i decyzje mogą przesuwać czas naprzód, dlatego nie da się pomóc wszystkim postaciom w jednym przejściu. Szczegóły praktyczne uzupełnimy po premierze na podstawie testów.", nav: ["Premiera", "Konsole"], source: "Oficjalna strona gry", checked: "27 sierpnia 2026" },
    "known-issues": { eyebrow: "STATUS PROBLEMÓW · RAPORTY GRACZY", title: "Znane problemy The Blood of Dawnwalker", dek: "Śledzimy awarie, wydajność i problemy z zadaniami, ale publikujemy rozwiązania dopiero po weryfikacji.", section: "Jak zgłaszać problem", body: "Dodaj platformę, wersję gry, ustawienia, dokładne kroki i nagranie lub zrzut ekranu. Pojedynczy wpis społeczności nie jest potwierdzonym problemem całej gry.", nav: ["Premiera", "Konsole"], source: "Centrum zgłoszeń", checked: "27 sierpnia 2026" },
  },
  ru: {
    "can-i-run": { eyebrow: "СОВМЕСТИМОСТЬ PC · ОФИЦИАЛЬНЫЕ ТРЕБОВАНИЯ", title: "Запустится ли The Blood of Dawnwalker на моём ПК?", dek: "Сверьте свой компьютер с официальными требованиями для PC.", section: "Важное ограничение", body: "Требования не гарантируют конкретный FPS: результат зависит от разрешения, настроек, драйверов и версии игры.", nav: ["Релиз", "Консоли"], source: "Официальные требования PC", checked: "27 августа 2026" },
    editions: { eyebrow: "ИЗДАНИЯ · ПРОВЕРЕННЫЕ ДАННЫЕ", title: "Издания The Blood of Dawnwalker", dek: "Сравнение состава изданий по материалам издателя без неподтверждённых бонусов.", section: "Как сравнивать издания", body: "Проверяйте цифровой контент, платформу и цену в региональном магазине. Название издания не означает ранний доступ без прямого подтверждения издателя.", nav: ["Релиз", "Консоли"], source: "Официальная страница игры", checked: "27 августа 2026" },
    "time-system": { eyebrow: "ВРЕМЯ В ИГРЕ · ПОДТВЕРЖДЁННЫЕ МЕХАНИКИ", title: "Система времени в The Blood of Dawnwalker", dek: "Что известно о 30 днях, последствиях заданий и выборе — без выдуманных способов остановить время.", section: "Что подтверждено", body: "Задания и решения могут продвигать время, поэтому нельзя помочь всем персонажам за одно прохождение. Практические детали появятся после проверок на релизе.", nav: ["Релиз", "Консоли"], source: "Официальная страница игры", checked: "27 августа 2026" },
    "known-issues": { eyebrow: "СТАТУС ПРОБЛЕМ · ОТЧЁТЫ ИГРОКОВ", title: "Известные проблемы The Blood of Dawnwalker", dek: "Мы отслеживаем вылеты, производительность и задания, но публикуем решения только после проверки.", section: "Как сообщить о проблеме", body: "Укажите платформу, версию игры, настройки, точные шаги и приложите запись или скриншот. Один пост сообщества не доказывает проблему всей игры.", nav: ["Релиз", "Консоли"], source: "Центр сообщений", checked: "27 августа 2026" },
  },
  cs: {
    "can-i-run": { eyebrow: "KOMPATIBILITA PC · OFICIÁLNÍ POŽADAVKY", title: "Spustí můj počítač The Blood of Dawnwalker?", dek: "Porovnejte svůj počítač s oficiálními požadavky pro PC.", section: "Důležité omezení", body: "Požadavky nezaručují konkrétní FPS; výsledek závisí na rozlišení, nastavení, ovladačích a verzi hry.", nav: ["Vydání", "Konzole"], source: "Oficiální požadavky PC", checked: "27. srpna 2026" },
    editions: { eyebrow: "EDICE · OVĚŘENÉ INFORMACE", title: "Edice The Blood of Dawnwalker", dek: "Srovnání obsahu edic podle materiálů vydavatele bez nepotvrzených bonusů.", section: "Jak porovnávat edice", body: "Ověřte digitální obsah, platformu a cenu v regionálním obchodě. Název edice neznamená dřívější přístup bez výslovného potvrzení vydavatele.", nav: ["Vydání", "Konzole"], source: "Oficiální stránka hry", checked: "27. srpna 2026" },
    "time-system": { eyebrow: "ČAS VE HŘE · POTVRZENÉ MECHANIKY", title: "Systém času v The Blood of Dawnwalker", dek: "Co víme o 30 dnech, důsledcích úkolů a volbách — bez vymyšlených způsobů, jak zastavit čas.", section: "Co je potvrzeno", body: "Úkoly a rozhodnutí mohou posouvat čas, proto nelze během jednoho průchodu pomoci všem postavám. Praktické podrobnosti doplníme po ověření při vydání.", nav: ["Vydání", "Konzole"], source: "Oficiální stránka hry", checked: "27. srpna 2026" },
    "known-issues": { eyebrow: "STAV PROBLÉMŮ · HLÁŠENÍ HRÁČŮ", title: "Známé problémy The Blood of Dawnwalker", dek: "Sledujeme pády, výkon a úkoly, ale řešení zveřejňujeme až po ověření.", section: "Jak nahlásit problém", body: "Uveďte platformu, verzi hry, nastavení, přesné kroky a záznam nebo snímek obrazovky. Jeden příspěvek komunity nedokazuje problém celé hry.", nav: ["Vydání", "Konzole"], source: "Centrum hlášení", checked: "27. srpna 2026" },
  },
};

type DetailCopy = { answer: string; facts: string; choice: string; checklist: string; concern: string; advances: string; unknown: string; advice: string; status: string; report: string; standard: string };
const details: Record<Locale, DetailCopy> = {
  pl: { answer: "Krótka odpowiedź", facts: "Oficjalna zawartość", choice: "Jak wybrać", checklist: "Przed zakupem", concern: "Skąd obawa o 30 dni?", advances: "Co przesuwa czas w grze?", unknown: "Czego nadal nie potwierdzono", advice: "Praktyczna rada przed premierą", status: "Aktualny status", report: "Jak zgłosić problem", standard: "Jak weryfikujemy rozwiązania" },
  ru: { answer: "Короткий ответ", facts: "Официальное содержание", choice: "Как выбрать", checklist: "Перед покупкой", concern: "Почему игроков волнуют 30 дней?", advances: "Что продвигает время в игре?", unknown: "Что ещё не подтверждено", advice: "Практический совет до релиза", status: "Текущий статус", report: "Как сообщить о проблеме", standard: "Как мы проверяем решения" },
  cs: { answer: "Stručná odpověď", facts: "Oficiální obsah", choice: "Jak vybrat", checklist: "Před nákupem", concern: "Proč hráče zajímá 30 dní?", advances: "Co posouvá herní čas?", unknown: "Co stále není potvrzeno", advice: "Praktická rada před vydáním", status: "Aktuální stav", report: "Jak nahlásit problém", standard: "Jak ověřujeme řešení" },
};

function completeSections(locale: Locale, topic: Topic, item: (typeof copy)[Locale][Topic]) {
  const d = details[locale];
  const base = `/${locale}`;
  if (topic === "editions") return [
    { title: d.answer, body: <p><b>{locale === "ru" ? "Ни одно официальное издание не заявлено с ранним доступом." : "Żadna oficjalna edycja nie ma potwierdzonego wcześniejszego dostępu."}</b> {item.body}</p> },
    { title: d.facts, body: <div className="fact-grid"><p><b>Standard</b>{locale === "ru" ? "Базовая игра; подходящий предзаказ может включать раннее получение брони." : "Gra podstawowa; kwalifikujący się preorder może obejmować wcześniejsze odblokowanie pancerza."}</p><p><b>Eclipse</b>{locale === "ru" ? "Базовая игра, цифровой компендиум, комикс и саундтрек." : "Gra podstawowa, cyfrowe kompendium, komiks i ścieżka dźwiękowa."}</p><p><b>Day One</b>{locale === "ru" ? "Физическая игра, Steelbook и карта мира." : "Fizyczna gra, Steelbook i mapa świata."}</p><p><b>Collector&apos;s</b>{locale === "ru" ? "Коллекционные физические предметы и цифровые материалы Eclipse." : "Kolekcjonerskie dodatki fizyczne oraz materiały cyfrowe Eclipse."}</p></div> },
    { title: d.choice, body: <ul><li>{locale === "ru" ? "Standard — если нужна только игра." : "Standard — jeśli potrzebujesz tylko gry."}</li><li>{locale === "ru" ? "Eclipse — только если cyfrowe materiały mają wartość przy lokalnej cenie." : "Eclipse — tylko jeśli cyfrowe dodatki są warte lokalnej ceny."}</li><li>{locale === "ru" ? "Day One и Collector’s — для физических предметов, не для другого времени разблокировки." : "Day One i Collector’s — dla przedmiotów fizycznych, nie dla innej godziny odblokowania."}</li></ul> },
    { title: d.checklist, body: <ul><li>{locale === "ru" ? "Проверьте название издания и текст бонуса именно в своём магазине." : "Sprawdź nazwę edycji i opis bonusu w swoim sklepie."}</li><li>{locale === "ru" ? "Не считайте дату регионального магазина доказательством раннего доступа." : "Nie uznawaj daty w regionalnym sklepie za dowód wcześniejszego dostępu."}</li><li>{locale === "ru" ? "Сохраните подтверждение покупки и описание прав." : "Zachowaj potwierdzenie zakupu oraz opis uprawnień."}</li></ul> },
  ];
  if (topic === "time-system") return [
    { title: d.answer, body: <p><b>{locale === "ru" ? "Подтверждённого отсчёта в реальном времени нет." : "Nie potwierdzono odliczania w czasie rzeczywistym."}</b> {item.body}</p> },
    { title: d.concern, body: <div className="fact-grid"><p><b>{locale === "ru" ? "Опасение" : "Obawa"}</b>{locale === "ru" ? "Игроки боятся, что исследование лишит их сюжетного контента." : "Gracze obawiają się, że eksploracja odbierze im zawartość fabularną."}</p><p><b>{locale === "ru" ? "Смысл системы" : "Sens systemu"}</b>{locale === "ru" ? "Время — ресурс для выбора обязательств, а не секундомер." : "Czas jest zasobem do wyboru zobowiązań, a nie stoperem."}</p><p><b>{locale === "ru" ? "Это не обещает" : "To nie jest obietnica"}</b>{locale === "ru" ? "Одnego przejścia ze wszystkimi zadaniami ani trybu bez limitu." : "Jednego przejścia ze wszystkimi zadaniami ani trybu bez limitu."}</p><p><b>{locale === "ru" ? "Главный вопрос" : "Najważniejsze pytanie"}</b>{locale === "ru" ? "Что именно тратит сегменты времени и как ясно игра показывает koszt." : "Co zużywa segmenty czasu i jak jasno gra pokazuje koszt."}</p></div> },
    { title: d.advances, body: <div className="fact-grid"><p><b>{locale === "ru" ? "Прогресс заданий" : "Postęp zadań"}</b>{locale === "ru" ? "Взятие lub ukończenie określonych celów przesuwa czas." : "Podejmowanie lub kończenie określonych celów przesuwa czas."}</p><p><b>{locale === "ru" ? "Смена дня и ночи" : "Zmiana dnia i nocy"}</b>{locale === "ru" ? "Официальный opis wskazuje ją jako działanie przesuwające czas." : "Oficjalny opis wskazuje ją jako działanie przesuwające czas."}</p><p><b>{locale === "ru" ? "Исследование" : "Eksploracja"}</b>{locale === "ru" ? "Между punktами прогресса есть неограниченное реальное время." : "Między punktami postępu jest nieograniczony czas rzeczywisty."}</p><p><b>{locale === "ru" ? "Последствия" : "Konsekwencje"}</b>{locale === "ru" ? "Невозможно помочь всем персонажам в одном прохождении." : "Nie można pomóc wszystkim postaciom w jednym przejściu."}</p></div> },
    { title: d.unknown, body: <p>{locale === "ru" ? "Режим без таймера, точная стоимость каждого действия и свободное исследование после финала не подтверждены. Не доверяйте советам по «отключению 30 дней» до повторяемой проверки на версии релиза." : "Nie potwierdzono trybu bez limitu, dokładnego kosztu każdej czynności ani swobodnej eksploracji po finale. Nie ufaj poradom o „wyłączeniu 30 dni” przed powtarzalnym testem wersji premierowej."}</p> },
    { title: d.advice, body: <p>{locale === "ru" ? "Если ta mechanika decyduje o zakupie, дождитесь теста версии релиза z pokazaniem zadania, eksploracji i ekranu czasu." : "Jeśli ta mechanika decyduje o zakupie, poczekaj na test wersji premierowej pokazujący zadanie, eksplorację i ekran czasu."}</p> },
  ];
  if (topic === "known-issues") return [
    { title: d.status, body: <div className="fact-grid"><p><b>{locale === "ru" ? "Официальное обновление" : "Oficjalna aktualizacja"}</b>{locale === "ru" ? "Целевые 60 FPS dla PS5, PS5 Pro i Series X." : "Cel 60 FPS dla PS5, PS5 Pro i Series X."}</p><p><b>{locale === "ru" ? "Подтверждённые баги" : "Potwierdzone błędy"}</b>{locale === "ru" ? "Нет подтверждённых записей до релиза." : "Brak potwierdzonych wpisów przed premierą."}</p><p><b>{locale === "ru" ? "Спекуляции" : "Spekulacje"}</b>{locale === "ru" ? "Не публикуются как решения." : "Nie są publikowane jako rozwiązania."}</p><p><b>{locale === "ru" ? "Требования к отчёту" : "Wymagania zgłoszenia"}</b>{locale === "ru" ? "Платформа, версия, kroki i dowód." : "Platforma, wersja, kroki i dowód."}</p></div> },
    { title: d.report, body: <p>{locale === "ru" ? "Сообщайте о вылетах, производительности, блокировках заданий и проблемах магазина только с платформой, версией, настройками и точными шагами. Не включайте личные данные, данные аккаунта или частные сохранения." : "Zgłaszaj awarie, wydajność, blokady zadań i problemy sklepu tylko z platformą, wersją, ustawieniami i dokładnymi krokami. Nie dodawaj danych osobowych, danych konta ani prywatnych zapisów."}</p> },
    { title: d.standard, body: <ul><li>{locale === "ru" ? "Официальное исправление требует ссылки на издателя, владельца платформы или patch notes." : "Oficjalna poprawka wymaga linku do wydawcy, właściciela platformy lub patch notes."}</li><li>{locale === "ru" ? "Обход требует повторяемых kroków i niezależnego potwierdzenia." : "Obejście wymaga powtarzalnych kroków i niezależnego potwierdzenia."}</li><li>{locale === "ru" ? "Непроверенные сообщения остаются непроверенными." : "Niezweryfikowane zgłoszenia pozostają niezweryfikowane."}</li></ul> },
  ];
  return [{ title: item.section, body: <p>{item.body}</p> }];
}

export function generateStaticParams() { return locales.flatMap((locale) => topics.map((topic) => ({ locale, topic }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; topic: string }> }) { const { locale, topic } = await params; if (!locales.includes(locale as Locale) || !topics.includes(topic as Topic)) return {}; const item = copy[locale as Locale][topic as Topic]; return regionalMetadata(locale as "ru" | "cs", item.title, item.dek, `/${locale}/${topic}`, [item.title]); }
export default async function LocalizedInfoPage({ params }: { params: Promise<{ locale: string; topic: string }> }) { const { locale, topic } = await params; if (!locales.includes(locale as Locale) || !topics.includes(topic as Topic)) notFound(); const normalizedLocale = locale as Locale; const normalizedTopic = topic as Topic; const item = copy[normalizedLocale][normalizedTopic]; return <RegionalGuidePage locale={normalizedLocale} eyebrow={item.eyebrow} title={item.title} dek={item.dek} checked={item.checked} homeLabel="" releaseLabel={item.nav[0]} consoleLabel={item.nav[1]} checkedLabel="✓" sourcesLabel="Sources" footer="Dawnwalker Guide" sources={[{ label: item.source, href: "https://www.bandainamcoent.com/games/dawnwalker" }]} sections={completeSections(normalizedLocale, normalizedTopic, item)} />; }
