import { RegionalGuidePage } from "./regional-guide";

type Locale = "pl" | "ru";
type Topic = "release-date" | "console-performance";

const sourceRelease = [
  { label: "Bandai Namco — release announcement", href: "https://en.bandainamcoent.eu/dawnwalker/news/the-blood-of-dawnwalker-will-launch-september-3-rebel-wolves-revealed-key-details" },
  { label: "Official community — global release timings", href: "https://www.reddit.com/r/DawnwalkerOfficial/comments/1vxyko5/dawnwalker_global_release_timings_are_here/" },
];
const sourceConsole = [{ label: "Rebel Wolves — Day One performance announcement", href: "https://www.reddit.com/r/DawnwalkerOfficial/comments/1vwxe1r/the_blood_of_dawnwalker_will_receive_a/" }];

export function LocalizedFullGuide({ locale, topic }: { locale: Locale; topic: Topic }) {
  const ru = locale === "ru";
  const release = topic === "release-date";
  const title = release ? (ru ? "The Blood of Dawnwalker — дата и время выхода" : "The Blood of Dawnwalker — data i godzina premiery") : (ru ? "The Blood of Dawnwalker: 60 FPS на PS5 и режимы Xbox" : "The Blood of Dawnwalker: 60 FPS na PS5 i tryby Xbox");
  const dek = release ? (ru ? "Игра выходит 3 сентября 2026 года на PC, PlayStation 5 и Xbox Series X|S. Здесь собраны дата, правила разблокировки на PC и консолях, а также подтверждённый статус предзагрузки." : "Gra wychodzi 3 września 2026 roku na PC, PlayStation 5 i Xbox Series X|S. Zebraliśmy datę, zasady odblokowania na PC i konsolach oraz potwierdzony status preloadu.") : (ru ? "PS5, PS5 Pro и Xbox Series X нацелены на Performance Mode 60 FPS на релизе. «Цель» не означает независимо подтверждённые стабильные 60 FPS в каждой сцене." : "PS5, PS5 Pro i Xbox Series X celują w 60 FPS w trybie wydajności na premierę. „Cel” nie oznacza niezależnie potwierdzonego stałego 60 FPS w każdej scenie.");
  const releaseSections = [
    { title: ru ? "Кратко о релизе" : "Premiera w skrócie", body: <div className="fact-grid"><p><b>{ru ? "Дата" : "Data"}</b>{ru ? "3 сентября 2026" : "3 września 2026"}</p><p><b>{ru ? "Платформы" : "Platformy"}</b>PC, PS5, Xbox Series X|S</p><p><b>{ru ? "Разработчик" : "Twórcy"}</b>Rebel Wolves</p><p><b>{ru ? "Жанр" : "Gatunek"}</b>{ru ? "Экшен-RPG в открытом мире" : "Fabularna gra akcji w otwartym świecie"}</p></div> },
    { title: ru ? "PC: единый момент, а не ранний доступ" : "PC: jeden moment, nie wcześniejszy dostęp", body: <><p><b>{ru ? "PC разблокируется одновременно во всём мире в полночь CEST (UTC+2, Варшава)." : "PC odblokowuje się jednocześnie na całym świecie o północy CEST (UTC+2, Warszawa)."}</b> {ru ? "В Америке в этот момент ещё 2 сентября, поэтому Steam может корректно показывать 2 сентября. Это не ранний доступ." : "W Amerykach jest wtedy jeszcze 2 września, dlatego Steam może poprawnie pokazywać 2 września. To nie jest wcześniejszy dostęp."}</p><div className="fact-grid"><p><b>Los Angeles (PDT)</b>{ru ? "2 сентября · 15:00" : "2 września · 15:00"}</p><p><b>New York (EDT)</b>{ru ? "2 сентября · 18:00" : "2 września · 18:00"}</p><p><b>Warsaw (CEST)</b>{ru ? "3 сентября · 00:00" : "3 września · 00:00"}</p><p><b>Tokyo (JST)</b>{ru ? "3 сентября · 07:00" : "3 września · 07:00"}</p></div></> },
    { title: ru ? "Консоли: важные региональные исключения" : "Konsole: ważne wyjątki regionalne", body: <><p><b>{ru ? "На консолях обычно действует местная полночь." : "Na konsolach zasadą jest północ czasu lokalnego."}</b> {ru ? "Издатель указывает исключения для Северной и Южной Америки (полночь EDT), а также Австралии, Индонезии и других стран с несколькими часовыми поясами (столичный часовой пояс)." : "Wydawca wskazuje wyjątki dla Ameryki Północnej i Południowej (północ EDT) oraz Australii, Indonezji i innych państw z wieloma strefami (czas stolicy)."}</p><p>{ru ? "Не выводите консольное время из таблицы PC: окончательной проверкой остаётся таймер PlayStation или Xbox для вашего региона." : "Nie wyprowadzaj godziny na konsoli z tabeli PC — ostatecznym sprawdzeniem pozostaje odliczanie w sklepie PlayStation lub Xbox dla konta."}</p></> },
    { title: ru ? "Предзагрузка и ранний доступ" : "Preload i wcześniejszy dostęp", body: <p>{ru ? "Сообщение о времени релиза подтверждает правила разблокировки, но не указывает единый график предзагрузки или размер файла. Также ни Standard, ни Eclipse, Day One или Collector’s Edition не заявлены с ранним доступом." : "Komunikat o godzinach premiery potwierdza zasady odblokowania, ale nie podaje jednego harmonogramu preloadu ani rozmiaru pliku. Żadna z edycji Standard, Eclipse, Day One ani Collector’s nie ma też potwierdzonego wcześniejszego dostępu."}</p> },
    { title: ru ? "Проверка в день релиза" : "Kontrola w dniu premiery", body: <ul><li>{ru ? "Проверьте регион аккаунта и версию игры." : "Sprawdź region konta i wersję gry."}</li><li>{ru ? "Установите обновление первого дня перед созданием сохранения." : "Zainstaluj aktualizację z dnia premiery przed rozpoczęciem zapisu."}</li><li>{ru ? "При проблеме сохраните клип, платформу, версию и шаги." : "Przy problemie zapisz klip, platformę, wersję i kroki."}</li></ul> },
  ];
  const consoleSections = [
    { title: ru ? "Короткий ответ: PS5 нацелена на 60 FPS" : "Krótka odpowiedź: PS5 celuje w 60 FPS", body: <p><b>{ru ? "Да: в патче первого дня заявлен Performance Mode с целью 60 FPS для PS5, PS5 Pro и Xbox Series X." : "Tak: patch na pierwszy dzień zapowiada tryb wydajności celujący w 60 FPS na PS5, PS5 Pro i Xbox Series X."}</b> {ru ? "Это цель разработчиков, а не обещание стабильной частоты в каждой сцене без независимого теста." : "To cel twórców, a nie obietnica stałej liczby klatek w każdej scenie bez niezależnego testu."}</p> },
    { title: ru ? "Официальные цели на релиз" : "Oficjalne cele na premierę", body: <div className="fact-grid"><p><b>PS5 Pro</b>{ru ? "Производительность 60 · Баланс 40 · Качество 30 FPS" : "Wydajność 60 · Zrównoważony 40 · Jakość 30 FPS"}</p><p><b>PS5</b>{ru ? "Производительность 60 · Баланс 40 · Качество 30 FPS" : "Wydajność 60 · Zrównoważony 40 · Jakość 30 FPS"}</p><p><b>Xbox Series X</b>{ru ? "Производительность 60 · Баланс 40 · Качество 30 FPS" : "Wydajność 60 · Zrównoważony 40 · Jakość 30 FPS"}</p><p><b>Xbox Series S</b>{ru ? "Цель: 30 FPS" : "Cel: 30 FPS"}</p></div> },
    { title: ru ? "Перед выбором платформы" : "Przed wyborem platformy", body: <ul><li>{ru ? "Убедитесь, что патч первого дня установлен." : "Upewnij się, że patch z dnia premiery jest zainstalowany."}</li><li>{ru ? "Не считайте формулировку «цель 60 FPS» независимым тестом." : "Nie traktuj sformułowania „cel 60 FPS” jako niezależnego testu."}</li><li>{ru ? "Дождитесь обзоров с версией патча, сценой, настройками и VRR." : "Poczekaj na testy z wersją patcha, sceną, ustawieniami i VRR."}</li></ul> },
    { title: ru ? "Стандарт отчёта сообщества" : "Standard raportu społeczności", body: <p>{ru ? "Для полезного отчёта укажите модель консоли, режим, версию патча, частоту обновления/VRR, локацию и клип. Один ролик не является тестом всей платформы." : "W użytecznym raporcie podaj model konsoli, tryb, wersję patcha, odświeżanie/VRR, lokację i klip. Jeden film nie jest testem całej platformy."}</p> },
  ];
  return <RegionalGuidePage locale={locale} eyebrow={release ? (ru ? "ГИД ПО РЕЛИЗУ · ОФИЦИАЛЬНЫЕ ДАННЫЕ" : "PORADNIK PREMIERY · OFICJALNE INFORMACJE") : (ru ? "ПРОИЗВОДИТЕЛЬНОСТЬ НА КОНСОЛЯХ · ПАТЧ ПЕРВОГО ДНЯ" : "WYDAJNOŚĆ NA KONSOLACH · PATCH NA PREMIERĘ")} title={title} dek={dek} checked={ru ? "28 августа 2026" : "28 sierpnia 2026"} homeLabel="" releaseLabel="" consoleLabel="" checkedLabel={ru ? "Проверено" : "Sprawdzono"} sourcesLabel={ru ? "Источники" : "Źródła"} footer={ru ? "Неофициальный фан-гид." : "Nieoficjalny poradnik fanowski."} sources={release ? sourceRelease : sourceConsole} sections={release ? releaseSections : consoleSections} />;
}
