import type { Metadata } from "next";

export const metadata: Metadata = { alternates: { canonical: "/" } };

const cards = [
  ["Release date", "When does The Blood of Dawnwalker release?", "September 3, 2026. See supported platforms, time zones and official sources.", "/release-date"],
  ["Platforms", "PC, PS5 & Xbox guide", "What is confirmed for each platform, including the launch performance-mode update.", "/platforms"],
  ["Romance", "Romance options and relationships", "A spoiler-conscious tracker. We separate confirmed facts from what still needs testing.", "/romance"],
];

export default function Home() {
  return <main><nav className="nav"><a className="brand" href="/">DAWN<span>ARCHIVE</span><small>INDEPENDENT FIELD GUIDE</small></a><div className="links"><a href="/release-date">Release</a><a href="/platforms">Platforms</a><a href="/romance">Romance</a><a href="#launch">Launch desk</a></div></nav>
    <section className="hero" id="top"><div className="hero-art" aria-hidden="true"><img src="/dawnwalker-hero.jpg" alt="" /></div><div className="hero-copy"><p className="eyebrow">THE BLOOD OF DAWNWALKER · INDEPENDENT GUIDE</p><p className="hero-kicker">VERIFIED FACTS · SPOILER-AWARE HELP</p><h1>Your guide to <em>surviving the dawn.</em></h1><p className="lead">Release information, platform answers and player-first guides for Rebel Wolves&apos; dark-fantasy action RPG—clearly marked as official, verified, or still unconfirmed.</p><div className="hero-actions"><a className="primary" href="/release-date">Release date & times</a><a className="secondary" href="#launch">Launch help desk</a></div></div><aside className="clock-card"><p>GLOBAL RELEASE</p><div className="day">SEP <span>03</span></div><div className="bar"><i /></div><small>2026 · PC, PlayStation 5<br />Xbox Series X|S</small></aside></section>
    <section className="signal"><span>✦ LAUNCH STATUS</span><p>Release is confirmed for September 3, 2026. We update facts with dated official sources and label community reports before they become advice.</p><a href="/release-date">Check the release guide →</a></section>
    <section className="section intro"><div><p className="eyebrow">USEFUL, NOT NOISY</p><h2>Answers for the moment you need them.</h2></div><div className="intro-copy"><p>We build pages around a player&apos;s question—not a list of duplicate keywords. Every guide names its evidence, date checked and spoiler level.</p><span>OFFICIAL · VERIFIED · COMMUNITY REPORT</span></div></section>
    <section className="section"><div className="section-head"><div><p className="eyebrow">START HERE</p><h2>High-intent guides.</h2></div></div><div className="route-grid">{cards.map(([tag,title,text,href], index) => <article className={`feature-card ${index === 0 ? "crimson" : index === 1 ? "night-card" : "archive-card"}`} key={href}><span>0{index + 1} · {tag}</span><h3>{title}</h3><p>{text}</p><a href={href}>Open guide →</a></article>)}</div></section>
    <section id="launch" className="section planner"><div className="planner-copy"><p className="eyebrow">LAUNCH HELP DESK</p><h2>Turn player reports into reliable answers.</h2><p>On launch week we monitor public reports for crashes, performance, quests and platform-specific issues. We publish reproducible fixes only after checking the report and mark workarounds by confidence.</p><div className="hero-actions"><a className="primary" href="https://github.com/wencun/dawnwalker.cc/issues/new/choose" target="_blank" rel="noreferrer">Report an issue</a><a className="secondary" href="https://github.com/wencun/dawnwalker.cc/issues" target="_blank" rel="noreferrer">Browse known issues</a></div></div><div className="quest-panel launch-panel"><p className="eyebrow">HOW A REPORT MOVES</p><ol><li><b>Collect</b><span>Player report or public community signal</span></li><li><b>Verify</b><span>Platform, game version and reproducible steps</span></li><li><b>Publish</b><span>Fix, workaround or a clear “under investigation” status</span></li></ol><p className="note">No invented fixes. Community reports are never presented as official statements.</p></div></section>
    <section className="section library"><div className="section-head"><div><p className="eyebrow">EDITORIAL STANDARD</p><h2>Built for citation and trust.</h2></div></div><div className="library-grid"><div><strong>01</strong><span>Official source links</span></div><div><strong>02</strong><span>Last-checked dates</span></div><div><strong>03</strong><span>Spoiler labels</span></div><div><strong>04</strong><span>Corrections welcome</span></div></div></section>
    <footer><a className="brand" href="/">Dawn<span>Archive</span></a><p>Unofficial fan guide. The Blood of Dawnwalker and related marks belong to their respective owners.<br/><a href="/privacy">Privacy</a> · <a href="https://github.com/wencun/dawnwalker.cc/issues" target="_blank" rel="noreferrer">Corrections & feedback</a></p><span>EST. 2026</span></footer>
  </main>;
}
